language: python

python:
  - 3.5

cache: pip

install:
  - pip install -q -r requirements.txt
  - pip install -q pylint
  - pip install -q codecov

script:
  - bash run_pylint.sh
  - bash run_tests.sh
  - python3 demo.py --train_iteration=1000 -l=0.001 --enable_cuda=False

after_success:
  - codecov

notifications:
  email: false

branches:
  only:
    - master
